version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gradle"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    files:
      - "libs.versions.toml"