files:
  - source: /instafel.app/src/main/res/values/strings.xml
    translation: /instafel.app/src/main/res/values-%android_code%/strings.xml
  - source: /instafel.website/src/locales/en/**/*.json
    translation: /instafel.website/src/locales/%locale%/%original_file_name%
  - source: /instafel.updater/src/main/res/values/strings.xml
    translation: /instafel.updater/src/main/res/values-%android_code%/strings.xml
