name: Build & Deploy Website

on:
  push:
    branches:
      - main 
    paths:
      - 'instafel.website/**'
      - 'config/**'
      - 'settings.gradle.kts'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Install deps
        run: ./gradlew :instafel.website:install

      - name: Build project
        run: ./gradlew :instafel.website:build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_API_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./instafel.website
