# Workflow: Patch Instagram Alpha
# 
# This workflow automates the process of downloading Instagram Alpha APKs and patching them with Instafel.
# 
# Usage:
#   1. Manual trigger via workflow_dispatch with APK URL input (recommended)
#   2. Automatic download via gplayapi (requires GitHub Secrets configuration)
#
# Outputs:
#   - Patched Instagram APK files (clone and unclone variants)
#   - Build metadata JSON files
#
# See .github/workflows/README.md for detailed documentation

name: Patch Instagram Alpha

on:
  workflow_dispatch:
    inputs:
      instagram_apk_url:
        description: 'Instagram Alpha APK download URL (required if not using gplayapi)'
        required: false
        type: string
      instagram_version:
        description: 'Instagram version (for naming, optional)'
        required: false
        type: string
        default: 'latest'
      use_gplayapi:
        description: 'Use gplayapi to download latest Instagram Alpha (requires secrets)'
        required: false
        type: boolean
        default: true

jobs:
  patch-instagram:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Build Instafel App (Debug)
        run: |
          echo "Building Instafel App (Debug)..."
          ./gradlew :app:generate-app-debug
          ls -lh .output/
      
      - name: Build Instafel App (Release)
        run: |
          echo "Building Instafel App (Release)..."
          ./gradlew :app:generate-app-release
          ls -lh .output/
      
      - name: Build Patcher Core
        run: |
          echo "Building Patcher Core..."
          ./gradlew :patcher-core:build-jar
          ls -lh .output/
      
      - name: Build Instafel Patcher
        run: |
          echo "Building Instafel Patcher..."
          ./gradlew :patcher:build-jar
          ls -lh .output/
      
      - name: Download Instagram Alpha APK (Direct URL)
        if: ${{ !inputs.use_gplayapi && github.event.inputs.instagram_apk_url != '' }}
        run: |
          echo "Downloading Instagram Alpha APK from provided URL..."
          wget -O instagram-alpha.apk "${{ github.event.inputs.instagram_apk_url }}"
          ls -lh instagram-alpha.apk
      
      - name: Setup gplayapi and download (if enabled)
        if: ${{ inputs.use_gplayapi }}
        run: |
          echo "Setting up gplayapi to download Instagram Alpha..."
          
          # Create config.properties file from GitHub Secrets
          cat > config.properties << EOF
          email=${{ secrets.GPLAY_EMAIL }}
          aas_token=${{ secrets.GPLAY_AAS_TOKEN }}
          github_pat=${{ secrets.GH_TOKEN }}
          EOF
          
          # Build gplayapi downloader
          echo "Building gplayapi downloader..."
          ./gradlew :gplayapi:downloaderJar
          ls -lh .output/
          
          # Run the downloader
          echo "Downloading Instagram Alpha APK..."
          java -jar .output/ifl-gplayapi-downloader-*.jar instagram-alpha.apk
          
          echo "Download completed:"
          ls -lh instagram-alpha.apk
      
      - name: Validate APK exists
        run: |
          if [ ! -f instagram-alpha.apk ]; then
            echo "Error: instagram-alpha.apk not found"
            echo "Please provide instagram_apk_url parameter"
            exit 1
          fi
          echo "APK file validated:"
          ls -lh instagram-alpha.apk
      
      - name: Setup patcher environment
        run: |
          # Copy core JAR to current directory so patcher can find it locally
          cp .output/ifl-patcher-core-*.jar .
          echo "Core JAR copied to current directory:"
          ls -lh ifl-patcher-core-*.jar

          
      - name: List Instafel patches
        run: |
          # Run init command to extract and prepare the APK
          java -jar .output/ifl-patcher-v*.jar list
          
      - name: Initialize Instafel project
        run: |
          # Run init command to extract and prepare the APK
          java -jar .output/ifl-patcher-v*.jar init instagram-alpha.apk
          
          # Verify project was created
          PROJECT_DIR=$(ls -d instagram-* 2>/dev/null | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: Project directory not found after init"
            ls -la
            exit 1
          fi
          
          echo "Project initialized successfully: $PROJECT_DIR"
          ls -la "$PROJECT_DIR"
      
      - name: Apply patches (unclone variant)
        run: |
          # Find the project directory
          PROJECT_DIR=$(ls -d instagram-* 2>/dev/null | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: Project directory not found"
            exit 1
          fi
          
          echo "Applying Instafel patches (unclone variant) to: $PROJECT_DIR"
          java -jar .output/ifl-patcher-v*.jar run "$PROJECT_DIR" instafel ghost_mode
          
          echo "Unclone patches applied successfully"
      
      - name: Build patched Instagram APK (unclone variant)
        run: |
          # Find the project directory
          PROJECT_DIR=$(ls -d instagram-* 2>/dev/null | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: Project directory not found"
            exit 1
          fi
          
          echo "Building patched APK (unclone variant) for: $PROJECT_DIR"
          java -jar .output/ifl-patcher-v*.jar build "$PROJECT_DIR"
          
          # Verify build output
          if [ ! -d "$PROJECT_DIR/build" ]; then
            echo "Error: Build directory not created"
            exit 1
          fi
          
          # Rename the APK to indicate it's the unclone variant
          for apk in "$PROJECT_DIR/build/"*.apk; do
            if [ -f "$apk" ]; then
              base=$(basename "$apk" .apk)
              mv "$apk" "$PROJECT_DIR/build/${base}-unclone.apk"
            fi
          done
          
          echo "Build completed successfully (unclone variant)"
          echo "Build output:"
          ls -lh "$PROJECT_DIR/build/"
      
      - name: Apply patches (clone variant)
        run: |
          # Find the project directory
          PROJECT_DIR=$(ls -d instagram-* 2>/dev/null | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: Project directory not found"
            exit 1
          fi
          
          echo "Applying clone patches to: $PROJECT_DIR"
          java -jar .output/ifl-patcher-v*.jar run "$PROJECT_DIR" clone
          
          echo "Clone patches applied successfully"
      
      - name: Build patched Instagram APK (clone variant)
        run: |
          # Find the project directory
          PROJECT_DIR=$(ls -d instagram-* 2>/dev/null | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: Project directory not found"
            exit 1
          fi
          
          echo "Building patched APK (clone variant) for: $PROJECT_DIR"
          java -jar .output/ifl-patcher-v*.jar build "$PROJECT_DIR"
          
          # Verify build output
          if [ ! -d "$PROJECT_DIR/build" ]; then
            echo "Error: Build directory not created"
            exit 1
          fi
          
          # Rename the APK to indicate it's the clone variant
          for apk in "$PROJECT_DIR/build/"*.apk; do
            if [ -f "$apk" ] && [[ ! "$apk" =~ "-unclone.apk" ]]; then
              base=$(basename "$apk" .apk)
              mv "$apk" "$PROJECT_DIR/build/${base}-clone.apk"
            fi
          done
          
          echo "Build completed successfully (clone variant)"
          echo "Build output:"
          ls -lh "$PROJECT_DIR/build/"
      
      - name: Upload Instafel App APKs
        uses: actions/upload-artifact@v4
        with:
          name: instafel-app-${{ github.event.inputs.instagram_version }}
          path: .output/ifl-app-*.apk
          if-no-files-found: warn
      
      - name: Upload Patcher JAR
        uses: actions/upload-artifact@v4
        with:
          name: instafel-patcher-${{ github.event.inputs.instagram_version }}
          path: .output/ifl-patcher-v*.jar
          if-no-files-found: warn
      
      - name: Upload Patcher Core JAR
        uses: actions/upload-artifact@v4
        with:
          name: instafel-patcher-core-${{ github.event.inputs.instagram_version }}
          path: .output/ifl-patcher-core-*.jar
          if-no-files-found: warn
      
      - name: Upload patched Instagram APKs
        uses: actions/upload-artifact@v4
        with:
          name: instafel-patched-instagram-${{ github.event.inputs.instagram_version }}
          path: instagram-*/build/*.apk
          if-no-files-found: warn
      
      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: instafel-build-info-${{ github.event.inputs.instagram_version }}
          path: instagram-*/build/*.json
          if-no-files-found: warn
